- name: Gather services facts
  ansible.builtin.service_facts:

- name: Install keycloak if not installed
  ansible.builtin.include_tasks: install.yml
  # when: '"keycloak.service" not in ansible_facts.services'

- name: Config keycloak
  ansible.builtin.include_tasks: config.yml
