---
- name: Install essentials
  ansible.builtin.apt:
    update_cache: true
    name:
      - vim
      - molly-guard
      - htop
      - iftop
    state: present

- name: Color ls
  ansible.builtin.blockinfile:
    path: /root/.bashrc
    marker: "# {mark} ANSIBLE COLOR LS"
    block: |
      export LS_OPTIONS='--color=auto'
      eval "`dircolors`"
      alias ls='ls $LS_OPTIONS'
      alias ll='ls $LS_OPTIONS -l'
      alias l='ls $LS_OPTIONS -lA'

- name: Color root shell
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    regexp: ^export PS1=
    line: export PS1='\[\033[00;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00;31m\]\$\[\033[00m\] '

- name: Generate MOTD banner
  ansible.builtin.shell: figlet {{ ansible_hostname | quote }} -f slant -w 120 | lolcat --force-color --seed {{ 65535 | random(seed=inventory_hostname) }}
  delegate_to: localhost
  become: false
  register: common_motd
  changed_when: common_motd.rc != 0
  ignore_errors: true

- name: Copy MOTD banner
  ansible.builtin.template:
    src: 00-banner.j2
    dest: /etc/update-motd.d/00-banner
    mode: "755"
  when: not common_motd.failed
