- name: Download Vault Hashicorp gpg key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
    mode: "0644"
    owner: root
    checksum: sha256:cafb01beac341bf2a9ba89793e6dd2468110291adfbb6c62ed11a0cde6c09029

- name: Pin Vault package
  ansible.builtin.template:
    src: vault.pref.j2
    dest: /etc/apt/preferences.d/vault.pref
    mode: '0644'
    owner: root
    group: root

- name: Add Vault repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: Install Vault
  ansible.builtin.apt:
    update_cache: true
    name:
      - vault

- name: Retrieve role_id and secret_id from Vault
  community.hashi_vault.vault_kv2_get:
    path: certificat-web-id
  register: vault_agent_certificates_secrets
  run_once: true
  delegate_to: localhost
  become: false

- name: Create vault agent workdir
  ansible.builtin.file:
    path: "{{ vault_agent_working_directory }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create role_id file
  vars:
    content: "{{ vault_agent_certificates_secrets.secret.role_id }}"
  ansible.builtin.template:
    src: content.j2
    dest: "{{ vault_agent_working_directory }}/role_id"
    mode: '0600'
    owner: root
    group: root

- name: Create secret_id file
  vars:
    content: "{{ vault_agent_certificates_secrets.secret.secret_id }}"
  ansible.builtin.template:
    src: content.j2
    dest: "{{ vault_agent_working_directory }}/secret_id"
    mode: '0600'
    owner: root
    group: root

- name: Copy agent-config.hcl
  ansible.builtin.template:
    src: agent-config.hcl.j2
    dest: "{{ vault_agent_working_directory }}/agent-config.hcl"
    mode: '0644'
    owner: root
    group: root
  notify: Restart vault-agent-certificates

- name: Copy retrieving_cert.tmpl
  ansible.builtin.template:
    src: retrieving_cert.tmpl.j2
    dest: "{{ vault_agent_working_directory }}/retrieving_cert.tmpl"
    mode: '0644'
    owner: root
    group: root
    variable_start_string: '<<'
    variable_end_string: '>>'
  notify: Restart vault-agent-certificates

- name: Copy vault-agent-certificates.service
  ansible.builtin.template:
    src: vault-agent-certificates.service.j2
    dest: /etc/systemd/system/vault-agent-certificates.service
    mode: '0644'
    owner: root
    group: root

- name: Create read-access group
  ansible.builtin.group:
    name: "{{ vault_agent_group_name }}"

- name: Create directory for certificates
  ansible.builtin.file:
    state: directory
    dest: "{{ vault_agent_certificate_directory }}"
    mode: '0755'
    owner: root
    group: "{{ vault_agent_group_name }}"

- name: Start vault-agent-certificates service
  ansible.builtin.systemd:
    name: vault-agent-certificates
    state: started
    enabled: true
    daemon_reload: true
